#!/usr/bin/env python3
"""
Follow-Up Email Generator (LLM-powered)
Generates follow-up email drafts from meeting transcripts using LLM.
"""
import logging
from pathlib import Path
from typing import Dict, Any, List, Optional
from blocks.llm_client import get_client

logger = logging.getLogger(__name__)


async def generate_follow_up_email(
    transcript: str,
    meeting_info: Dict[str, Any],
    email_history: Optional[List[Dict]],
    meeting_history: List[Dict],
    meeting_types: List[str],
    output_dir: Path
) -> bool:
    """
    Generate follow-up email draft using LLM.
    
    Args:
        transcript: Full meeting transcript text
        meeting_info: Extracted meeting metadata
        email_history: Previous email exchanges (optional)
        meeting_history: Previous meetings with stakeholder
        meeting_types: Types of meeting
        output_dir: Directory to write output file
        
    Returns:
        True if successful, False otherwise
    """
    try:
        logger.info("Generating follow-up email using LLM")
        
        llm = get_client()
        
        # Read action items and decisions if available
        action_items = _read_file(output_dir / "action-items.md")
        decisions = _read_file(output_dir / "decisions.md")
        
        # Determine relationship context
        relationship_stage = "new" if len(meeting_history) == 0 else \
                           "developing" if len(meeting_history) <= 2 else "established"
        
        meeting_type_str = ', '.join(meeting_types) if meeting_types else "general"
        
        system_prompt = f"""You are an expert at writing professional follow-up emails after meetings.

Context:
- Meeting type: {meeting_type_str}
- Relationship stage: {relationship_stage}
- Previous meetings: {len(meeting_history)}

Write a follow-up email that:
1. Thanks them for their time
2. Recaps key points discussed
3. Confirms next steps and action items
4. Maintains appropriate tone for the relationship
5. Is concise and actionable

For coaching meetings: be warm and supportive
For sales/partnerships: be professional and value-focused
For established relationships: be familiar but respectful"""

        stakeholder = meeting_info.get('stakeholder_primary', 'Unknown')
        date = meeting_info.get('date', 'today')
        participants = meeting_info.get('participants', [])
        
        user_prompt = f"""Generate a follow-up email for this meeting.

Meeting Date: {date}
Stakeholder: {stakeholder}
Participants: {', '.join(participants) if participants else 'Unknown'}

Meeting Transcript (for context):
{transcript[:10000]}

Action Items Summary:
{action_items[:2000] if action_items else "No action items file available"}

Decisions Summary:
{decisions[:2000] if decisions else "No decisions file available"}

Generate the email with:
- Subject line
- Appropriate greeting
- Brief recap paragraph
- Key decisions (if any)
- Next steps/action items
- Appropriate closing

Return the email in markdown format with clear sections."""

        response = await llm.generate(
            prompt=user_prompt,
            system=system_prompt,
            max_tokens=1500,
            temperature=0.7
        )
        
        # Format the response
        markdown = _format_email_markdown(response, stakeholder, date)
        
        # Write output
        output_path = output_dir / "follow-up-email.md"
        output_path.write_text(markdown, encoding='utf-8')
        
        logger.info("Generated follow-up email draft")
        return True
        
    except Exception as e:
        logger.error(f"Failed to generate follow-up email: {e}", exc_info=True)
        return False


def _read_file(path: Path) -> str:
    """Read file content, return empty string if not exists."""
    try:
        return path.read_text(encoding='utf-8')
    except:
        return ""


def _format_email_markdown(content: str, stakeholder: str, date: str) -> str:
    """Format email content as structured markdown."""
    md = "# Follow-Up Email Draft\n\n"
    md += f"**Stakeholder**: {stakeholder}\n"
    md += f"**Meeting Date**: {date}\n\n"
    md += "---\n\n"
    md += content
    md += "\n\n---\n\n"
    md += "_Note: This is a draft generated by AI. Please review and customize before sending._\n"
    return md
