#!/usr/bin/env python3
"""
Contextual Primer: Generate context blocks for B33 extraction.

Reads the resonance_index.json and produces a "What V Already Knows" section
that gets injected into extraction prompts. This allows the LLM to distinguish
between truly novel ideas and V's established mental models.

Usage:
    python3 contextual_primer.py generate          # Output context block to stdout
    python3 contextual_primer.py generate -o FILE  # Save to file
    python3 contextual_primer.py inject PROMPT     # Inject into existing prompt file
"""

import argparse
import json
from pathlib import Path
from datetime import datetime, timezone
from typing import Dict, List, Optional

# Paths
N5_DATA_DIR = Path("/home/workspace/N5/data")
RESONANCE_INDEX_PATH = N5_DATA_DIR / "resonance_index.json"


def load_resonance_index() -> Dict:
    """Load the current resonance index."""
    if not RESONANCE_INDEX_PATH.exists():
        raise FileNotFoundError(
            f"Resonance index not found at {RESONANCE_INDEX_PATH}. "
            "Run pattern_surfacer.py generate first."
        )
    return json.loads(RESONANCE_INDEX_PATH.read_text())


def format_idea_entry(idea: Dict, include_contexts: bool = True) -> str:
    """Format a single idea for the context block."""
    slug = idea["idea_slug"]
    label = idea.get("label") or slug.replace("-", " ").title()
    freq = idea["frequency"]
    
    line = f"- **{label}** (`{slug}`) — {freq} sessions"
    
    if include_contexts and idea.get("sample_contexts"):
        contexts = ", ".join(idea["sample_contexts"][:3])
        line += f" | contexts: {contexts}"
    
    return line


def generate_context_block(
    include_sparks: bool = False,
    max_cornerstones: int = 15,
    max_theses: int = 10,
    max_tools: int = 20,
    max_sparks: int = 10
) -> str:
    """
    Generate the contextual primer block for B33 extraction.
    
    This block tells the LLM what V already knows, so it can:
    1. Skip re-extracting Cornerstones unless there's evolution
    2. Track Active Theses for development, not repetition
    3. Note when Recurring Tools appear in new domains
    4. Focus extraction energy on genuine Sparks
    """
    index = load_resonance_index()
    
    lines = []
    lines.append("<!-- CONTEXTUAL PRIMER: V's Established Mental Models -->")
    lines.append("<!-- Generated by resonance/contextual_primer.py -->")
    lines.append(f"<!-- Index date: {index.get('generated_at', 'unknown')} -->")
    lines.append("")
    lines.append("## V's Intellectual Context")
    lines.append("")
    lines.append("Before extracting edges, understand that V has established patterns.")
    lines.append("Use this context to distinguish NOVELTY from REPETITION.")
    lines.append("")
    
    # Cornerstones (L0)
    cornerstones = index.get("cornerstones", [])[:max_cornerstones]
    if cornerstones:
        lines.append("### 🏛️ Cornerstones (Foundational Beliefs)")
        lines.append("These ideas are V's bedrock. Do NOT re-extract them UNLESS:")
        lines.append("- V explicitly **challenges** or **revises** the idea")
        lines.append("- The idea is applied to a **genuinely new domain**")
        lines.append("- Someone **disputes** V's position on this")
        lines.append("")
        for idea in cornerstones:
            lines.append(format_idea_entry(idea))
        lines.append("")
    
    # Active Theses (L1)
    active_theses = index.get("active_theses", [])[:max_theses]
    if active_theses:
        lines.append("### 🔬 Active Theses (Ideas V Is Developing)")
        lines.append("These ideas are in active development. When you see them:")
        lines.append("- Extract ONLY if there's **evolution**: new evidence, refinement, pivot")
        lines.append("- Include `evolution_type` field: `refinement`, `expansion`, `challenge`")
        lines.append("- Note what's NEW about this mention vs. previous")
        lines.append("")
        for idea in active_theses:
            lines.append(format_idea_entry(idea))
        lines.append("")
    
    # Recurring Tools (L2)
    recurring_tools = index.get("recurring_tools", [])[:max_tools]
    if recurring_tools:
        lines.append("### 🔧 Recurring Tools (Frameworks V Reaches For)")
        lines.append("These are mental models V applies repeatedly. When you see them:")
        lines.append("- Extract ONLY if applied to a **new domain** or **combined** in a new way")
        lines.append("- Note the domain/context where it's being applied")
        lines.append("- Skip if it's the same application as before")
        lines.append("")
        for idea in recurring_tools:
            lines.append(format_idea_entry(idea, include_contexts=True))
        lines.append("")
    
    # Sparks (L3) - optional, usually not included
    if include_sparks:
        recent_sparks = index.get("recent_sparks", [])[:max_sparks]
        if recent_sparks:
            lines.append("### ✨ Recent Sparks (For Reference)")
            lines.append("These appeared recently. If you see them again, they may be graduating to L2.")
            lines.append("")
            for idea in recent_sparks:
                lines.append(format_idea_entry(idea, include_contexts=False))
            lines.append("")
    
    # Extraction guidance
    lines.append("### 📋 Extraction Rules (Given This Context)")
    lines.append("")
    lines.append("1. **For Cornerstones**: Only extract if EVOLUTION detected. Use relation `evolves` with `evolution_type`.")
    lines.append("2. **For Active Theses**: Extract evolution, skip mere repetition. Include what's NEW.")
    lines.append("3. **For Recurring Tools**: Note new domain applications. Skip same-domain repetition.")
    lines.append("4. **For Novel Ideas**: Extract fully! These are the valuable Sparks.")
    lines.append("5. **When in doubt**: Ask \"Is this genuinely new thinking, or V restating what he already believes?\"")
    lines.append("")
    lines.append("<!-- END CONTEXTUAL PRIMER -->")
    
    return "\n".join(lines)


def generate_compact_context() -> str:
    """
    Generate a compact version for injection into existing prompts.
    Uses less tokens but preserves key information.
    """
    index = load_resonance_index()
    
    lines = []
    lines.append("<!-- V's Known Ideas (skip unless evolution) -->")
    
    # Combine all non-spark ideas into a compact list
    known_ideas = []
    
    for idea in index.get("cornerstones", []):
        known_ideas.append(f"{idea['idea_slug']}(L0:{idea['frequency']})")
    
    for idea in index.get("active_theses", []):
        known_ideas.append(f"{idea['idea_slug']}(L1:{idea['frequency']})")
    
    for idea in index.get("recurring_tools", [])[:25]:  # Limit to top 25
        known_ideas.append(f"{idea['idea_slug']}(L2:{idea['frequency']})")
    
    lines.append(f"KNOWN: {', '.join(known_ideas)}")
    lines.append("RULE: Only extract KNOWN ideas if there's evolution/challenge/new-domain.")
    lines.append("<!-- End context -->")
    
    return "\n".join(lines)


def inject_into_prompt(prompt_path: str, output_path: Optional[str] = None) -> str:
    """
    Inject the contextual primer into an existing prompt file.
    Looks for <!-- INJECT_CONTEXT --> marker or prepends to content.
    """
    prompt_file = Path(prompt_path)
    if not prompt_file.exists():
        raise FileNotFoundError(f"Prompt file not found: {prompt_path}")
    
    content = prompt_file.read_text()
    context_block = generate_context_block()
    
    # Look for injection marker
    marker = "<!-- INJECT_CONTEXT -->"
    if marker in content:
        new_content = content.replace(marker, context_block)
    else:
        # Prepend after frontmatter if present
        if content.startswith("---"):
            # Find end of frontmatter
            end_idx = content.find("---", 3)
            if end_idx != -1:
                frontmatter = content[:end_idx + 3]
                body = content[end_idx + 3:]
                new_content = f"{frontmatter}\n\n{context_block}\n{body}"
            else:
                new_content = f"{context_block}\n\n{content}"
        else:
            new_content = f"{context_block}\n\n{content}"
    
    # Save if output path provided
    if output_path:
        Path(output_path).write_text(new_content)
        return f"Injected context into: {output_path}"
    
    return new_content


def get_stats() -> Dict:
    """Get summary statistics from the resonance index."""
    index = load_resonance_index()
    return {
        "generated_at": index.get("generated_at"),
        "total_ideas": index.get("total_ideas", 0),
        "cornerstones": len(index.get("cornerstones", [])),
        "active_theses": len(index.get("active_theses", [])),
        "recurring_tools": len(index.get("recurring_tools", [])),
        "sparks": len(index.get("recent_sparks", []))
    }


def main():
    parser = argparse.ArgumentParser(
        description="Generate contextual primers for B33 extraction"
    )
    subparsers = parser.add_subparsers(dest="command", required=True)
    
    # Generate command
    gen_parser = subparsers.add_parser("generate", help="Generate context block")
    gen_parser.add_argument("-o", "--output", help="Output file path")
    gen_parser.add_argument("--compact", action="store_true", help="Generate compact version")
    gen_parser.add_argument("--include-sparks", action="store_true", help="Include recent sparks")
    
    # Inject command
    inject_parser = subparsers.add_parser("inject", help="Inject into existing prompt")
    inject_parser.add_argument("prompt", help="Path to prompt file")
    inject_parser.add_argument("-o", "--output", help="Output file (default: modify in place)")
    
    # Stats command
    subparsers.add_parser("stats", help="Show resonance index stats")
    
    args = parser.parse_args()
    
    if args.command == "generate":
        if args.compact:
            output = generate_compact_context()
        else:
            output = generate_context_block(include_sparks=args.include_sparks)
        
        if args.output:
            Path(args.output).write_text(output)
            print(f"Context block saved to: {args.output}")
        else:
            print(output)
            
    elif args.command == "inject":
        output_path = args.output or args.prompt
        result = inject_into_prompt(args.prompt, output_path)
        print(result)
        
    elif args.command == "stats":
        stats = get_stats()
        print(json.dumps(stats, indent=2))


if __name__ == "__main__":
    main()

