#!/usr/bin/env python3
"""
Stakeholder Profile Auto-Creation Workflow v2

ARCHITECTURE:
- Python handles ALL mechanics (scan, read, write, track)
- LLM handles ALL semantics (understand, analyze, generate)

This script orchestrates the workflow but does NOT generate content itself.
Content generation is done by calling back to the LLM (via return to chat).
"""

import json
import sys
from pathlib import Path
from typing import Dict, List

# Add N5 scripts to path
sys.path.insert(0, str(Path(__file__).parent))

from stakeholder_profile_collector import StakeholderDataCollector


class StakeholderProfileWorkflow:
    """
    Workflow orchestrator - coordinates mechanics with LLM semantics
    """
    
    def __init__(self):
        self.collector = StakeholderDataCollector()
    
    def prepare_llm_batch(self, limit: int = None) -> Dict:
        """
        Prepare batch of stakeholders for LLM processing.
        Returns data structure ready for LLM analysis.
        
        Args:
            limit: Maximum number of stakeholders to process (None = all)
        
        Returns:
            Dict with stakeholder data formatted for LLM
        """
        # Collect new stakeholders (pure mechanics)
        stakeholders = self.collector.collect_for_llm_processing()
        
        if limit:
            # Take first N
            stakeholders = dict(list(stakeholders.items())[:limit])
        
        # Format for LLM processing
        batch = {
            'total_stakeholders': len(stakeholders),
            'stakeholders': []
        }
        
        for identifier, meetings in stakeholders.items():
            # Extract basic info mechanically
            first_meeting = meetings[0]
            name = first_meeting.get('extracted_name', 'Unknown')
            email = first_meeting.get('extracted_email')
            
            stakeholder_data = {
                'identifier': identifier,
                'name': name,
                'email': email,
                'meeting_count': len(meetings),
                'meetings': []
            }
            
            # Include B08 and B01 content from each meeting
            for meeting in meetings:
                stakeholder_data['meetings'].append({
                    'date': meeting['meeting_date'],
                    'meeting_name': meeting['meeting_name'],
                    'b08_content': meeting['b08_content'],
                    'b01_content': meeting['b01_content']
                })
            
            batch['stakeholders'].append(stakeholder_data)
        
        return batch
    
    def save_profile_from_llm(self, identifier: str, name: str, 
                              profile_content: str, meetings_count: int) -> Path:
        """
        Save profile content generated by LLM.
        Pure mechanics - LLM has already done the semantic work.
        
        Args:
            identifier: Email or unique identifier
            name: Person's name
            profile_content: Full markdown content (generated by LLM)
            meetings_count: Number of meetings
        
        Returns:
            Path to saved profile
        """
        # Write file (mechanics)
        filepath = self.collector.write_profile(identifier, name, profile_content)
        
        # Log to database (mechanics)
        self.collector.log_to_database(identifier, name, meetings_count, str(filepath))
        
        return filepath


def main(dry_run: bool = True, limit: int = 3):
    """
    Main entry point for workflow.
    
    In dry-run mode: Just shows what would be processed
    In live mode: Returns data for LLM to process
    
    Args:
        dry_run: If True, only show preview
        limit: Max stakeholders to process in one batch
    """
    workflow = StakeholderProfileWorkflow()
    
    print("=" * 60)
    print("STAKEHOLDER PROFILE AUTO-CREATION v2")
    print("=" * 60)
    print()
    
    # Prepare batch
    batch = workflow.prepare_llm_batch(limit=limit if not dry_run else 3)
    
    print(f"📋 Found {batch['total_stakeholders']} stakeholders needing profiles")
    print()
    
    if dry_run:
        print("🔍 DRY RUN - Preview of first 3:")
        print()
        for stakeholder in batch['stakeholders']:
            print(f"  • {stakeholder['name']} ({stakeholder['email'] or 'no email'})")
            print(f"    Meetings: {stakeholder['meeting_count']}")
            for meeting in stakeholder['meetings']:
                print(f"      - {meeting['date']}: {meeting['meeting_name']}")
            print()
        
        print("=" * 60)
        print("To process, call with dry_run=False")
        print("LLM will then read B08 content and generate rich profiles")
        return None
    
    else:
        print("🚀 LIVE MODE - Returning data for LLM processing")
        print()
        
        # In live mode, return the batch so LLM can process it
        # The calling context (prompt/workflow) will handle LLM interaction
        return batch


if __name__ == "__main__":
    # Standalone execution = dry run
    main(dry_run=True)

