#!/usr/bin/env python3
"""
N5 File Protection System - Intelligent protection based on file role
"""

import os
import sys
import subprocess
from pathlib import Path
from typing import Optional, List

# Import backup system
try:
    from file_backup import FileBackupSystem
    BACKUP_AVAILABLE = True
except ImportError:
    BACKUP_AVAILABLE = False
    print("⚠️  Backup system not available")


class FileProtector:
    """Enhanced file protection for N5 OS based on architectural role"""
    
    # File classification based on your actual architecture
    HARD_PROTECTION_FILES = [
        "/home/workspace/Documents/N5.md",     # Core system index (hand-authored)
        "/home/workspace/N5/prefs/prefs.md",   # System preferences (hand-authored)
    ]
    
    MEDIUM_PROTECTION_FILES = [
        "/home/workspace/N5/commands.jsonl",  # Command registry (curated)
        "/home/workspace/Lists/*.jsonl",   # User data (curated)
        "/home/workspace/N5/timeline/system-timeline.jsonl", # System development timeline (curated)
        "/home/workspace/Knowledge/careerspan-timeline.md", # Company & life timeline (curated)
    ]
    
    AUTO_GENERATED_PATTERNS = [
        "/N5/index.md",                     # Generated by index-update
        "/N5/index.jsonl",                  # Database regenerated
        "/N5/commands.md",                  # Generated by docgen
        "/N5/commands/*.md",                # Auto-generated command docs
    ]
    
    def __init__(self):
        self.workspace_root = "/home/workspace"
    
    def classify_file(self, file_path: str) -> dict:
        """Classify a file based on its role in your N5 architecture"""
        str_path = str(Path(file_path).absolute())
        
        # Check hard protection (manual-edit only)
        if str_path in self.HARD_PROTECTION_FILES:
            return {"protection_level": "hard", "regeneratable": False, "classification": "core-governance"}
        
        # Check medium protection (curated content)
        if str_path in self.MEDIUM_PROTECTION_FILES:
            return {"protection_level": "medium", "regeneratable": False, "classification": "curated-data"}
        
        # Check auto-generated patterns
        for pattern in self.AUTO_GENERATED_PATTERNS:
            if pattern in str_path:
                return {"protection_level": "none", "regeneratable": True, "classification": "auto-generated"}
        
        # Check if under Knowledge (manually authored)
        if "/Knowledge/" in str_path:
            return {"protection_level": "medium", "regeneratable": False, "classification": "knowledge-content"}
        
        # Default classification
        return {"protection_level": "low", "regeneratable": False, "classification": "user-content"}
    
    def check_file_integrity(self, file_path: str) -> dict:
        """Check file state and integrity before modification"""
        path = Path(file_path)
        result = {
            "classification": self.classify_file(file_path),
            "file_exists": path.exists(),
            "has_content": False,
            "git_status": "unknown",
            "warnings": [],
            "can_modify": True
        }
        
        if not result["file_exists"]:
            return result
        
        # Check content
        try:
            with open(path, 'r') as f:
                content = f.read()
                result["has_content"] = len(content.strip()) > 0
                if result["has_content"] and result["classification"]["protection_level"] == "hard":
                    lines = content.splitlines()
                    result["warnings"].append(f"Critical file contains {len(lines)} lines of curated content")
        except Exception as e:
            result["warnings"].append(f"Cannot read file content: {e}")
        
        # Check Git status
        try:
            relative_path = str(path.relative_to(self.workspace_root))
            git_result = subprocess.run(
                ["git", "status", "--porcelain", relative_path],
                cwd=self.workspace_root,
                capture_output=True,
                text=True
            )
            if git_result.returncode == 0:
                if git_result.stdout.strip():
                    result["git_status"] = "modified"
                    result["warnings"].append(f"Git shows file as modified: {git_result.stdout.strip()}")
                else:
                    result["git_status"] = "clean"
            else:
                result["git_status"] = "not-tracked"
        except Exception:
            result["git_status"] = "error"
        
        # Determine if modification is allowed
        protection_level = result["classification"]["protection_level"]
        
        if protection_level == "hard" and result["has_content"]:
            result["can_modify"] = False
            result["warnings"].insert(0, "🚫 HARD PROTECTION: This file requires explicit manual approval for changes")
        
        return result
    
    def require_architectural_approval(self, file_path: str, operation: str, new_content: str) -> bool:
        """Require approval based on architectural role of the file"""
        integrity = self.check_file_integrity(file_path)
        classification = integrity["classification"]
        
        if classification["regeneratable"]:
            return True  # Auto-generated files can be freely overwritten
        
        if not integrity["warnings"] and not integrity["has_content"]:
            return True  # Safe to modify empty/untracked files
        
        print(f"\n{'='*60}")
        print(f"ARCHITECTURAL REVIEW: {Path(file_path).name}")
        print(f"{'='*60}")
        print(f"Classification: {classification['classification']} ({classification['protection_level'].upper()} protection)")
        print(f"Operation: {operation}")
        print(f"Regeneratable: {'Yes' if classification['regeneratable'] else 'No'}")
        
        for warning in integrity["warnings"]:
            print(f"⚠️  {warning}")
        
        # Create automatic backup for protected files
        if BACKUP_AVAILABLE and integrity["has_content"] and classification["protection_level"] in ["hard", "medium"]:
            print(f"\n🔒 Creating automatic backup before {operation}...")
            backup_system = FileBackupSystem()
            backup_path = backup_system.create_backup(file_path, operation)
            if backup_path:
                print(f"✅ Backup secured: {backup_path.name}")
            else:
                print(f"❌ Backup failed - recommend manual backup before proceeding")
        
        if classification["protection_level"] == "hard":
            print(f"\n❌ HARD PROTECTION ACTIVE")
            print("This file is hand-authored and requires explicit approval for any changes.")
            print("Alternative: Use append/insert operations instead of full replacement.")
        
        if integrity["has_content"] and classification["protection_level"] == "medium":
            print(f"\n✅ MEDIUM PROTECTION - Content-aware modification allowed")
            print("File contains curated content. Consider atomic changes vs replacement.")
            print(f"Current content length: {len(Path(file_path).read_text()) if integrity['has_content'] else 0} characters")
        
        # Could add interactive approval here if needed
        return integrity["can_modify"]


def main():
    """CLI interface for architectural file protection validation"""
    if len(sys.argv) < 2:
        print("Usage: python3 file_protector.py <file_path> [operation] [new_content_path]")
        print("Example: python3 file_protector.py /home/workspace/N5/prefs.md 'add commands' prefs_addition.md")
        sys.exit(1)
    
    file_path = sys.argv[1]
    operation = sys.argv[2] if len(sys.argv) > 2 else "modify"
    new_content = sys.argv[3] if len(sys.argv) > 3 else None
    
    protector = FileProtector()
    allowed = protector.require_architectural_approval(file_path, operation, new_content)
    
    classification = protector.classify_file(file_path)
    if allowed:
        print(f"✅ {classification['protection_level'].upper()} PROTECTION: Operation approved")
        sys.exit(0)
    else:
        print(f"❌ {classification['protection_level'].upper()} PROTECTION: Operation blocked for architectural safety")
        # Output structured data for N5 integration
        import json
        print(f"\n--N5-OUTPUT--")
        print(json.dumps({
            "classification": classification,
            "protection_allowed": allowed,
            "file_path": file_path
        }))
        sys.exit(1)


if __name__ == "__main__":
    main()