#!/usr/bin/env python3
"""
Tool Wrapper Generator for Intelligence Blocks
Generates executable wrapper scripts for each block type and registers them.
"""

import sqlite3
import json
import argparse
import logging
import uuid
from pathlib import Path

logging.basicConfig(level=logging.INFO, format="%(asctime)sZ %(levelname)s %(message)s")

# Paths
INTELLIGENCE_DIR = Path("/home/workspace/Intelligence")
BLOCKS_DB = INTELLIGENCE_DIR / "blocks.db"
EXECUTABLES_DB = Path("/home/workspace/N5/data/executables.db")
WRAPPERS_DIR = INTELLIGENCE_DIR / "tools"

def get_all_blocks():
    """Retrieve all production blocks from database."""
    conn = sqlite3.connect(BLOCKS_DB)
    conn.row_factory = sqlite3.Row
    cursor = conn.cursor()
    
    cursor.execute("""
        SELECT block_id, name, category, status, output_format
        FROM blocks
        WHERE status = 'active' AND block_id != 'B99'
        ORDER BY block_id
    """)
    
    blocks = [dict(row) for row in cursor.fetchall()]
    conn.close()
    return blocks

def generate_wrapper_script(block_id, block_name, category):
    """Generate a wrapper script for a block."""
    script_content = f'''#!/usr/bin/env python3
"""
Wrapper tool for generating {block_name} ({block_id})
Auto-generated by generate_tool_wrappers.py
"""

import sys
import argparse
import logging
from pathlib import Path

# Add scripts directory to path
sys.path.insert(0, str(Path(__file__).parent.parent / "scripts"))

from block_generator_engine import BlockGeneratorEngine

logging.basicConfig(level=logging.INFO, format="%(asctime)sZ %(message)s")

def main():
    parser = argparse.ArgumentParser(
        description="Generate {block_name} ({block_id})",
        formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument(
        "--meeting-id",
        required=True,
        help="Meeting ID (e.g., M01_2025-11-03_description)"
    )
    parser.add_argument(
        "--transcript-path",
        required=True,
        help="Path to meeting transcript file"
    )
    parser.add_argument(
        "--output-dir",
        help="Output directory (default: Intelligence/Blocks/<meeting_id>/)"
    )
    parser.add_argument(
        "--output-file",
        help="Specific output file path (overrides --output-dir)"
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Validate inputs without generating"
    )
    
    args = parser.parse_args()
    
    try:
        # Verify transcript exists
        transcript_path = Path(args.transcript_path)
        if not transcript_path.exists():
            logging.error(f"Transcript file not found: {{args.transcript_path}}")
            return 1
        
        if args.dry_run:
            logging.info(f"✓ Dry-run: Would generate {block_id} for meeting {{args.meeting_id}}")
            return 0
        
        # Generate block
        logging.info(f"Generating {block_id}: {block_name}...")
        engine = BlockGeneratorEngine()
        result = engine.generate_block(
            block_id="{block_id}",
            transcript_path=str(transcript_path),
            meeting_id=args.meeting_id,
            output_dir=args.output_dir,
            dry_run=False
        )
        
        if not result.get('success'):
            logging.error(f"Block generation failed: {{result.get('error')}}")
            return 1
        
        output_file = result.get('output_file')
        logging.info(f"✓ Generated: {{output_file}}")
        
        return 0
        
    except Exception as e:
        logging.error(f"Error: {{e}}", exc_info=True)
        return 1

if __name__ == "__main__":
    sys.exit(main())
'''
    
    return script_content

def create_wrapper_files(blocks, dry_run=False):
    """Create wrapper script files for all blocks."""
    WRAPPERS_DIR.mkdir(exist_ok=True, parents=True)
    
    created = []
    for block in blocks:
        block_id = block['block_id']
        name = block['name']
        category = block['category']
        
        # Generate filename (e.g., generate-b01)
        wrapper_name = f"generate-{block_id.lower()}"
        wrapper_path = WRAPPERS_DIR / wrapper_name
        
        if dry_run:
            logging.info(f"Would create: {wrapper_path}")
            continue
        
        # Generate and write script
        script_content = generate_wrapper_script(block_id, name, category)
        with open(wrapper_path, 'w') as f:
            f.write(script_content)
        
        # Make executable
        wrapper_path.chmod(0o755)
        
        created.append({
            'block_id': block_id,
            'name': name,
            'path': str(wrapper_path.absolute()),
            'wrapper_name': wrapper_name
        })
        
        logging.info(f"✓ Created {wrapper_name} ({name})")
    
    return created

def register_in_executables_db(wrappers, dry_run=False):
    """Register all wrappers in N5 executables database."""
    
    if not EXECUTABLES_DB.exists():
        logging.warning(f"Executables database not found: {EXECUTABLES_DB}")
        logging.info("Skipping registration (will need manual registration)")
        return 0
    
    conn = sqlite3.connect(EXECUTABLES_DB)
    cursor = conn.cursor()
    
    registered = 0
    for wrapper in wrappers:
        if dry_run:
            logging.info(f"Would register: {wrapper['wrapper_name']}")
            continue
        
        try:
            tool_id = f"tool_{wrapper['block_id'].lower()}_{uuid.uuid4().hex[:8]}"
            cursor.execute("""
                INSERT OR REPLACE INTO executables (
                    id, name, type, file_path, description, category, tags
                ) VALUES (?, ?, ?, ?, ?, ?, ?)
            """, (
                tool_id,
                wrapper['wrapper_name'],
                'tool',
                wrapper['path'],
                f"Generate {wrapper['name']} ({wrapper['block_id']})",
                'intelligence',
                json.dumps(['intelligence', 'block-generator', wrapper['block_id'].lower()])
            ))
            registered += 1
            logging.info(f"✓ Registered {wrapper['wrapper_name']}")
        except Exception as e:
            logging.error(f"Failed to register {wrapper['wrapper_name']}: {e}")
    
    conn.commit()
    conn.close()
    
    return registered

def main():
    parser = argparse.ArgumentParser(
        description="Generate tool wrappers for all Intelligence blocks"
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Show what would be created without creating files"
    )
    parser.add_argument(
        "--skip-registration",
        action="store_true",
        help="Skip registering in executables.db"
    )
    
    args = parser.parse_args()
    
    try:
        # Get all blocks
        logging.info("Reading blocks from database...")
        blocks = get_all_blocks()
        logging.info(f"Found {len(blocks)} production blocks")
        
        # Create wrapper scripts
        logging.info("\nGenerating wrapper scripts...")
        wrappers = create_wrapper_files(blocks, dry_run=args.dry_run)
        
        if not args.dry_run:
            logging.info(f"\n✓ Created {len(wrappers)} wrapper scripts in {WRAPPERS_DIR}")
        
        # Register in executables database
        if not args.skip_registration and not args.dry_run:
            logging.info("\nRegistering tools in executables database...")
            registered = register_in_executables_db(wrappers, dry_run=args.dry_run)
            logging.info(f"✓ Registered {registered} tools")
        elif args.dry_run:
            logging.info(f"\nWould register {len(wrappers)} tools in executables.db")
        
        # Summary
        logging.info("\n" + "="*60)
        logging.info("SUMMARY")
        logging.info("="*60)
        logging.info(f"Production blocks: {len(blocks)}")
        logging.info(f"Wrappers created: {len(wrappers)}")
        if not args.skip_registration:
            logging.info(f"Tools registered: {registered if not args.dry_run else len(wrappers)}")
        logging.info(f"Location: {WRAPPERS_DIR.absolute()}")
        logging.info("="*60)
        
        return 0
        
    except Exception as e:
        logging.error(f"Error: {e}", exc_info=True)
        return 1

if __name__ == "__main__":
    exit(main())
