#!/usr/bin/env python3
"""
Config Generator - Creates user_config/ from interview answers.

Generates:
- preferences.json (N5 system configuration)
- telemetry_settings.json
- README.md (explains user_config/)

Part of: N5 OS Core Phase 0.5
"""
import json
import logging
from pathlib import Path
from typing import Dict, Any
from datetime import datetime, timezone

logger = logging.getLogger(__name__)

class ConfigGenerator:
    """Generates user_config/ directory with personalized settings."""
    
    def __init__(self, user_config_path: Path):
        self.user_config = user_config_path
        self.templates_dir = Path(__file__).parent.parent / "templates"
    
    def create_user_config(self, preferences: Dict[str, Any]) -> None:
        """Create user_config/ directory with all files."""
        # Create directory
        self.user_config.mkdir(parents=True, exist_ok=True)
        logger.info(f"✓ Created directory: {self.user_config}")
        
        # Write preferences.json
        self._write_preferences(preferences)
        
        # Write telemetry_settings.json
        self._write_telemetry(preferences.get("telemetry_enabled", False))
        
        # Write README.md
        self._write_readme()
        
        logger.info("✓ Configuration files generated")
    
    def _write_preferences(self, prefs: Dict[str, Any]) -> None:
        """Write preferences.json."""
        prefs_file = self.user_config / "preferences.json"
        
        # Ensure all required sections exist
        config = {
            "version": prefs.get("version", "1.0.0"),
            "created": prefs.get("created", datetime.now(timezone.utc).isoformat()),
            "workflows": prefs.get("workflows", {}),
            "automation": prefs.get("automation", {}),
            "conversation_end": prefs.get("conversation_end", {}),
            "git": prefs.get("git", {}),
            "n5": prefs.get("n5", {})
        }
        
        prefs_file.write_text(json.dumps(config, indent=2))
        logger.info(f"✓ Created: {prefs_file}")
    
    def _write_telemetry(self, enabled: bool) -> None:
        """Write telemetry_settings.json."""
        telemetry_file = self.user_config / "telemetry_settings.json"
        
        config = {
            "enabled": enabled,
            "anonymous_id": None,
            "events_tracked": [] if not enabled else [
                "command_run",
                "script_execute",
                "error"
            ],
            "storage": "local_only",
            "last_event": None,
            "opt_in_date": datetime.now(timezone.utc).isoformat() if enabled else None
        }
        
        telemetry_file.write_text(json.dumps(config, indent=2))
        logger.info(f"✓ Created: {telemetry_file}")
    
    def _write_readme(self) -> None:
        """Write user_config/README.md."""
        readme_file = self.user_config / "README.md"
        
        content = """# Your N5 Configuration

**This directory contains your personal N5 OS Core settings.**

## What's Here

- `preferences.json` - Your N5 system configuration
- `telemetry_settings.json` - Telemetry opt-in/out
- `.onboarding_complete` - Setup completion marker
- `README.md` - This file

## Important

**This directory is `.gitignored` and NEVER committed to Git.**

Your personal configuration stays on your machine only.

## Customization

You can edit `preferences.json` anytime to change:
- Enabled workflow systems
- Automation level
- Scheduled tasks
- Conversation end behavior
- Git safety settings

After editing, your changes take effect immediately.

## Re-Onboarding

To reset and re-run onboarding:

```bash
python3 /home/workspace/n5os-core/N5/scripts/n5_onboard.py --reset
```

## Questions?

See: `Documents/System/ONBOARDING_GUIDE.md`

---

*Generated by N5 OS Core onboarding*
*Do not commit this directory to Git*
"""
        
        readme_file.write_text(content)
        logger.info(f"✓ Created: {readme_file}")
