#!/usr/bin/env python3
"""
Welcome Guide Generator - Creates personalized welcome documentation.

Generates:
- Welcome guide explaining N5 concepts
- Quick start guide for enabled workflows
- Tips based on configuration

Part of: N5 OS Core Phase 0.5
"""
import logging
from pathlib import Path
from typing import Dict, Any
from datetime import datetime

logger = logging.getLogger(__name__)

class WelcomeGuideGenerator:
    """Generates personalized welcome documentation."""
    
    def __init__(self, user_config_path: Path):
        self.user_config = user_config_path
        self.workspace = Path("/home/workspace/n5os-core")
    
    def generate(self, preferences: Dict[str, Any]) -> Path:
        """Generate personalized welcome guide."""
        guide_path = self.workspace / "Documents" / "WELCOME.md"
        
        content = self._build_guide(preferences)
        guide_path.write_text(content)
        
        logger.info(f"✓ Generated: {guide_path}")
        return guide_path
    
    def _build_guide(self, prefs: Dict[str, Any]) -> str:
        """Build welcome guide content."""
        enabled_workflows = [k for k, v in prefs["workflows"].items() if v]
        auto_level = prefs["automation"]["level"]
        
        guide = f"""# Welcome to N5 OS Core!

**Setup completed**: {datetime.now().strftime('%Y-%m-%d %H:%M')}  
**Your configuration**: `user_config/preferences.json`

---

## What You Just Configured

### Enabled Workflows

{self._format_workflows(prefs["workflows"])}

### Automation Level

**{auto_level.replace('-', ' ').title()}**

{self._explain_automation(auto_level)}

### Scheduled Tasks

{self._format_tasks(prefs["automation"]["tasks"]) if prefs["automation"]["scheduled_tasks_enabled"] else "*No scheduled tasks configured*"}

---

## Quick Start

### 1. Try Your First Command

```bash
# View available recipes
ls -la Recipes/

# Test conversation end
Type: /conversation-end
```

### 2. Explore Your Workspace

```
n5os-core/
├── Lists/          ← Manage actions and ideas
├── Knowledge/      ← Store learnings
├── Records/        ← Working documents
├── Recipes/        ← Custom commands
└── user_config/    ← Your personal settings
```

### 3. Customize Further

Edit your config anytime:
```bash
nano user_config/preferences.json
```

Changes take effect immediately.

---

## Enabled Systems Guide

{self._generate_system_guides(enabled_workflows)}

---

## Tips Based on Your Setup

{self._generate_tips(prefs)}

---

## Next Steps

1. **Read the docs**: `Documents/System/`
2. **Try a workflow**: {self._suggest_workflow(enabled_workflows)}
3. **Customize**: Edit `user_config/preferences.json`
4. **Get help**: Check `Documents/System/TROUBLESHOOTING.md`

---

## Need Help?

- **Documentation**: `Documents/System/`
- **Recipes**: `Recipes/*.md`
- **GitHub**: https://github.com/vrijenattawar/n5os-core
- **Issues**: https://github.com/vrijenattawar/n5os-core/issues

---

## Re-Onboarding

To reset and reconfigure:

```bash
python3 N5/scripts/n5_onboard.py --reset
```

---

**Enjoy your personalized N5 OS Core system!**

*Generated by N5 onboarding v0.5*
"""
        return guide
    
    def _format_workflows(self, workflows: Dict[str, bool]) -> str:
        """Format enabled workflows list."""
        lines = []
        descriptions = {
            "lists": "Manage actions, ideas, and must-contact items",
            "meetings": "Generate AARs and follow-ups",
            "digests": "Create daily summaries",
            "social": "Manage X/LinkedIn content",
            "crm": "Track relationships"
        }
        
        for name, enabled in workflows.items():
            status = "✅" if enabled else "⬜"
            desc = descriptions.get(name, "")
            lines.append(f"{status} **{name.title()}** - {desc}")
        
        return "\n".join(lines)
    
    def _explain_automation(self, level: str) -> str:
        """Explain automation level."""
        explanations = {
            "manual": "You'll trigger all workflows explicitly. Great for learning and control.",
            "semi-auto": "Zo suggests automations and waits for your approval. Recommended for most users.",
            "auto": "Scheduled tasks run automatically. Maximum productivity."
        }
        return explanations.get(level, "Custom automation configuration.")
    
    def _format_tasks(self, tasks: list) -> str:
        """Format scheduled tasks list."""
        if not tasks:
            return "*No tasks scheduled*"
        
        descriptions = {
            "index-rebuild": "Daily at 2 AM - Keeps Knowledge index current",
            "git-check": "Daily at 8 AM - Prevents accidental commits",
            "empty-files": "Weekly Sunday at 3 AM - Cleans up empty files",
            "list-review": "Weekly Friday at 4 PM - Reminds you to review Lists/"
        }
        
        lines = []
        for task in tasks:
            desc = descriptions.get(task, "Custom task")
            lines.append(f"- **{task}**: {desc}")
        
        return "\n".join(lines)
    
    def _generate_system_guides(self, enabled_workflows: list) -> str:
        """Generate quick guides for enabled systems."""
        if not enabled_workflows:
            return "*No workflows enabled. Enable them in `user_config/preferences.json`*"
        
        guides = []
        
        if "lists" in enabled_workflows:
            guides.append("""### Lists System

**Add action**:
```
Add to Lists/actions.jsonl: "Review Q4 metrics"
```

**View items**:
```bash
cat Lists/actions.jsonl | jq -r '.item'
```""")
        
        if "meetings" in enabled_workflows:
            guides.append("""### Meetings System

**After a meeting**:
```
Generate AAR for today's standup
```

AARs saved to: `Records/Meetings/`""")
        
        if "digests" in enabled_workflows:
            guides.append("""### Digests System

**Create daily digest**:
```
Generate digest for today
```

View in: `Documents/Digests/`""")
        
        if "social" in enabled_workflows:
            guides.append("""### Social System

**Draft a post**:
```
Draft X post about [topic]
```

Drafts saved to: `Records/Social/`""")
        
        if "crm" in enabled_workflows:
            guides.append("""### CRM System

**Track interaction**:
```
Log conversation with [name]
```

CRM data in: `Lists/crm.jsonl`""")
        
        return "\n\n".join(guides)
    
    def _generate_tips(self, prefs: Dict[str, Any]) -> str:
        """Generate personalized tips."""
        tips = []
        
        if prefs["automation"]["level"] == "semi-auto":
            tips.append("💡 **Semi-Auto Mode**: Zo will suggest automations but wait for your approval. Review suggestions carefully.")
        
        if prefs["git"]["safety_mode"] == "strict":
            tips.append("🔒 **Git Safety**: git-check will run before commits. This prevents accidentally committing `user_config/`.")
        
        if prefs["workflows"]["lists"]:
            tips.append("📝 **Lists**: End conversations with `/conversation-end` to auto-update your action items.")
        
        if not prefs["telemetry_enabled"]:
            tips.append("📊 **Telemetry**: You opted out. Enable in `user_config/telemetry_settings.json` to help improve N5.")
        
        if len(tips) == 0:
            tips.append("🚀 **Explore**: Try different recipes in `Recipes/` to discover what N5 can do.")
        
        return "\n\n".join(tips)
    
    def _suggest_workflow(self, enabled: list) -> str:
        """Suggest first workflow to try."""
        if "lists" in enabled:
            return "Add an action item to Lists/"
        elif "digests" in enabled:
            return "Generate a daily digest"
        elif "meetings" in enabled:
            return "Create a meeting AAR"
        else:
            return "Explore `Recipes/` directory"
