#!/bin/bash
# B99-Generated Rename Script
# Generated by manually simulating the automation process

set -e  # Exit on error

cd /home/workspace/Personal/Meetings || exit 1

echo "========================================="
echo "B99 Meeting Folder Renames"
echo "========================================="
echo ""

# Function to rename with safety checks
safe_rename() {
    local old="$1"
    local new="$2"
    
    if [ ! -d "$old" ]; then
        echo "❌ SKIP: $old (doesn't exist)"
        return 1
    fi
    
    if [ -d "$new" ]; then
        echo "⚠️  SKIP: $old → $new (target exists)"
        return 1
    fi
    
    echo "✅ $old"
    echo "   → $new"
    mv "$old" "$new"
    echo ""
}

# Execute renames (in date order)
safe_rename "2025-08-26_external_external" "2025-08-26_Asher-King-Abramson_partnership"
safe_rename "2025-08-27_external_external" "2025-08-27_Ashraf-Heleka_discovery"
safe_rename "2025-09-02_external_external" "2025-09-02_Aniket_partnership"
safe_rename "2025-09-08_advisory_external" "2025-09-08_Alex-Caveny_coaching"
safe_rename "2025-09-11_external_external" "2025-09-11_Caleb-Thornton_networking"
safe_rename "2025-09-12_external_external" "2025-09-12_greenlight_sales"
safe_rename "2025-09-18_advisory_external" "2025-09-18_Bram-Adams_advisory"
safe_rename "2025-10-09_external_external" "2025-10-09_Alex-Caveny_coaching"
safe_rename "2025-10-20_advisory_external" "2025-10-20_Bennett-Lee_advisory"
safe_rename "2025-10-22_external_external" "2025-10-22_Brinleigh-Murphy-Reuter_external"
safe_rename "2025-10-29_external_external" "2025-10-29_careerspan-team_daily-standup_standup"
safe_rename "2025-11-03_external_external" "2025-11-03_careerspan-team_ai-workflow-demo_planning"
safe_rename "2025-11-04_advisory_external" "2025-11-04_Bram-Adams_advisory"
safe_rename "2025-11-04_compliance_external" "2025-11-04_dbn-ctum_financial-review_partner"
safe_rename "2025-11-04_external_external" "2025-11-04_granola-team_zo-demo_workshop"

# Handle duplicates with -2 suffix
safe_rename "2025-08-27_external_external-2" "2025-08-27_community-partner_referral-networks_partnership"
safe_rename "2025-11-04_advisory_external-2" "2025-11-04_unknown-attendee_advisory"
safe_rename "2025-11-04_external_external-2" "2025-11-04_unknown-attendee_external"

echo "========================================="
echo "Rename complete!"
echo "========================================="
